# Generated by Django 4.1.4 on 2022-12-20 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('max_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('committee', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=512)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=32)),
                ('project_name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('start_date', models.DateField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cost', models.FloatField()),
                ('timespan', models.FloatField()),
                ('feedback', models.CharField(default='', max_length=1000)),
                ('rating', models.IntegerField(null=True)),
                ('goal', models.CharField(max_length=1000)),
                ('completion', models.FloatField(null=True)),
                ('actual_cost', models.FloatField(null=True)),
                ('is_accepted', models.BooleanField(default=True)),
                ('proposal_date', models.DateField(null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('est_completion_date', models.DateField(null=True)),
                ('exec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_id', models.CharField(max_length=32)),
                ('component_type', models.CharField(max_length=32)),
                ('budget_ratio', models.FloatField()),
                ('est_start_date', models.DateField(null=True)),
                ('est_completion_date', models.DateField(null=True)),
                ('depends_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
                ('executing_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
