# Generated by Django 4.1.4 on 2022-12-20 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(max_length=32)),
                ('code', models.CharField(max_length=32)),
                ('max_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('committee', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=256)),
                ('location', models.CharField(max_length=256)),
                ('start_date', models.DateField(null=True)),
                ('total_budget', models.CharField(max_length=32)),
                ('latitute', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cost', models.FloatField()),
                ('timespan', models.FloatField()),
                ('goal', models.CharField(max_length=1000)),
                ('completion', models.FloatField(null=True)),
                ('actual_cost', models.FloatField(null=True)),
                ('is_accepted', models.BooleanField(default=True)),
                ('proposal_date', models.DateField(null=True)),
                ('exec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('component_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('component_type', models.CharField(max_length=32)),
                ('budget_ratio', models.FloatField()),
                ('depends_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.component')),
                ('execution_agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agency')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
