# Generated by Django 4.1.4 on 2022-12-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=256)),
                ('category', models.CharField(max_length=256)),
                ('affiliated_agency', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=10000)),
                ('project_start_time', models.CharField(max_length=32)),
                ('project_completion_time', models.CharField(max_length=32)),
                ('total_budget', models.CharField(max_length=32)),
                ('completion_percentage', models.CharField(max_length=32)),
                ('location_coordinates', models.CharField(max_length=1000)),
            ],
        ),
    ]
