# Generated by Django 4.1.4 on 2022-12-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_completion_time',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_time',
            field=models.DateField(),
        ),
    ]
