# Generated by Django 4.1.4 on 2022-12-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=512)),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usertype')),
            ],
        ),
    ]
