# Generated by Django 4.1.4 on 2022-12-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='est_completion_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='est_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='est_completion_date',
            field=models.DateField(null=True),
        ),
    ]
