# Generated by Django 4.1.4 on 2022-12-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='total_budget',
        ),
    ]
