# Generated by Django 4.1.4 on 2022-12-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_project_total_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='latitute',
            new_name='latitude',
        ),
    ]
