# Generated by Django 4.1.4 on 2022-12-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_feedback_project_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='execution_agency',
            new_name='executing_agency',
        ),
        migrations.AddField(
            model_name='project',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
